# The CRS used for the output QGIS project file.
# All layers will be reprojected to this CRS.
crs: 'EPSG:3413'

boundaries:
  background: 'latitude_shape_45_degrees.geojson'
  data: 'greenland_with_blubber.geojson'
